# .github\workflows\build.yml
name: build and test
on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/demo-webapp
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/demo-webapp
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/demo-webapp
    - name: use this action, test solution dir
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: src/demo-webapp-test/demo-webapp-test.csproj
        report_name: demo-webapp-test-report
        report_title: Demo Webapp Test Report
        github_token: ${{ secrets.GITHUB_TOKEN }}