# .github\workflows\build.yml

name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_WEBAPP_NAME: ghworkflowactions
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Set up dependency caching for faster builds
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/demo-webapp
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/demo-webapp
  
  test:
    name: test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/demo-webapp-test
    
    - name: Testing Report
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: src/demo-webapp-test/demo-webapp-test.csproj
        report_name: demo-webapp-test-report
        report_title: Demo Webapp Test Report
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/demo-webapp-release
      working-directory: src/demo-webapp-test

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3      
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/demo-webapp-release

  deploy:
    permissions:
      contents: none

    runs-on: ubuntu-latest
    
    needs: test
    
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}